//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.Datos.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDRestaurantesEntities : DbContext
    {
        public BDRestaurantesEntities()
            : base("name=BDRestaurantesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_distrito> t_distrito { get; set; }
        public virtual DbSet<t_especialidadtipo> t_especialidadtipo { get; set; }
        public virtual DbSet<t_estado> t_estado { get; set; }
        public virtual DbSet<t_menu> t_menu { get; set; }
        public virtual DbSet<t_menudetalle> t_menudetalle { get; set; }
        public virtual DbSet<t_modoatencion> t_modoatencion { get; set; }
        public virtual DbSet<t_pago> t_pago { get; set; }
        public virtual DbSet<t_pedido> t_pedido { get; set; }
        public virtual DbSet<t_producto> t_producto { get; set; }
        public virtual DbSet<t_reserva> t_reserva { get; set; }
        public virtual DbSet<t_restaurante> t_restaurante { get; set; }
        public virtual DbSet<t_sesion> t_sesion { get; set; }
        public virtual DbSet<t_telefono> t_telefono { get; set; }
        public virtual DbSet<t_tipocomida> t_tipocomida { get; set; }
        public virtual DbSet<t_tipocta> t_tipocta { get; set; }
        public virtual DbSet<t_tipotelefono> t_tipotelefono { get; set; }
        public virtual DbSet<t_usuario> t_usuario { get; set; }
        public virtual DbSet<t_pedidodetalle> t_pedidodetalle { get; set; }
        public virtual DbSet<t_usuariocuenta> t_usuariocuenta { get; set; }
    }
}
