//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_pedidodetalle
    {
        public long pedi_id { get; set; }
        public long mede_id { get; set; }
        public Nullable<int> pedi_cant { get; set; }
        public Nullable<decimal> pedi_importe { get; set; }
    }
}
