//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_pedido
    {
        public long pedi_id { get; set; }
        public Nullable<System.DateTime> pedi_fechhora { get; set; }
        public Nullable<long> usua_id { get; set; }
        public string rest_ruc { get; set; }
        public Nullable<int> moat_id { get; set; }
        public string pedi_mensaje { get; set; }
        public string pedi_estado { get; set; }
        public Nullable<int> esta_id { get; set; }
        public Nullable<decimal> pedi_subtotal { get; set; }
        public Nullable<decimal> pedi_precioenvio { get; set; }
        public Nullable<decimal> pedi_descuento { get; set; }
        public Nullable<decimal> pedi_recargo { get; set; }
        public Nullable<decimal> pedi_total { get; set; }
    }
}
