//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_producto
    {
        public long prod_id { get; set; }
        public string prod_nombre { get; set; }
        public string prod_descrip { get; set; }
        public Nullable<decimal> prod_precio { get; set; }
        public Nullable<int> tico_id { get; set; }
        public string rest_ruc { get; set; }
    }
}
