//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_restaurante
    {
        public string rest_ruc { get; set; }
        public long usua_id { get; set; }
        public string rest_rz { get; set; }
        public string rest_nomcomer { get; set; }
        public Nullable<int> esti_id { get; set; }
        public string rest_descrip { get; set; }
        public Nullable<bool> rest_delivery { get; set; }
        public Nullable<bool> rest_reservalocal { get; set; }
        public Nullable<bool> rest_estado { get; set; }
    }
}
