//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sesion
    {
        public long sesi_id { get; set; }
        public Nullable<System.DateTime> sesi_fechhora { get; set; }
        public Nullable<long> usua_id { get; set; }
        public Nullable<bool> sesi_iniciada { get; set; }
        public Nullable<bool> sesi_estado { get; set; }
    }
}
