//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_usuariocuenta
    {
        public long usua_id { get; set; }
        public int ticta_id { get; set; }
        public string uscta_numero { get; set; }
        public string uscta_titular { get; set; }
        public int uscta_codigo { get; set; }
    }
}
